#!/usr/bin/env node
// Repository hygiene checks that no off-the-shelf linter covers. Zero dependencies.
//
//   node scripts/check-repo.mjs            json + html links + third-party requests + placeholders + secrets
//   node scripts/check-repo.mjs --history  also fail on AI co-author / "generated by" trailers in git history
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const problems = [];
const fail = (msg) => problems.push(msg);
const tracked = execFileSync('git', ['ls-files', '-z'], { cwd: ROOT, encoding: 'utf8' })
  .split('\0')
  .filter(Boolean);
const text = (file) => readFileSync(join(ROOT, file), 'utf8');
const isVendored = (file) => file.startsWith('vendor/') || file === 'package-lock.json';

// 1. every tracked *.json file parses
for (const file of tracked.filter((f) => f.endsWith('.json'))) {
  try {
    JSON.parse(text(file));
  } catch (err) {
    fail(`${file}: invalid JSON (${err.message})`);
  }
}

// 2. index.html: fragment targets, local files, third-party requests, target=_blank hygiene
const html = text('index.html');
const tags = [...html.matchAll(/<([a-z][a-z0-9-]*)\b([^>]*)>/gi)].map(([, name, attrs]) => ({
  name: name.toLowerCase(),
  attrs: Object.fromEntries([...attrs.matchAll(/([\w:-]+)\s*=\s*"([^"]*)"/g)].map(([, k, v]) => [k, v])),
}));
const ids = new Set(tags.map((t) => t.attrs.id).filter(Boolean));
const isRemote = (url) => /^(https?:)?\/\//i.test(url);
const localTarget = (url) => url.split(/[?#]/)[0];
const RESOURCE_ATTR = {
  script: 'src',
  link: 'href',
  img: 'src',
  source: 'src',
  iframe: 'src',
  video: 'src',
  audio: 'src',
  object: 'data',
};
const EXTERNAL_LINK_RELS = new Set(['canonical', 'alternate', 'author', 'license', 'me']);

for (const { name, attrs } of tags) {
  const href = attrs.href;
  if (name === 'a' && href?.startsWith('#') && href.length > 1 && !ids.has(href.slice(1)))
    fail(`index.html: ${href} has no matching id`);
  if (attrs.target === '_blank' && !/\bnoopener\b/.test(attrs.rel ?? ''))
    fail(`index.html: <${name} target="_blank"> needs rel="noopener" (${href})`);

  const attr = RESOURCE_ATTR[name];
  const url = attr && attrs[attr];
  if (!url) continue;
  if (isRemote(url)) {
    if (!(name === 'link' && EXTERNAL_LINK_RELS.has(attrs.rel)))
      fail(`index.html: third-party request <${name} ${attr}="${url}">`);
  } else if (!url.startsWith('data:') && !existsSync(join(ROOT, localTarget(url)))) {
    fail(`index.html: <${name} ${attr}="${url}"> does not exist`);
  }
}

const importMap = html.match(/<script type="importmap">([\s\S]*?)<\/script>/)?.[1];
if (importMap) {
  for (const [spec, url] of Object.entries(JSON.parse(importMap).imports ?? {})) {
    if (isRemote(url)) fail(`index.html: import map entry "${spec}" points to a third-party host (${url})`);
    else if (!existsSync(join(ROOT, url)))
      fail(`index.html: import map entry "${spec}" -> ${url} does not exist`);
  }
}

// 3. CSS: no remote @import/url(), local url() targets exist
for (const file of tracked.filter((f) => f.endsWith('.css'))) {
  const css = text(file);
  if (/@import\s+(url\()?['"]?(https?:)?\/\//i.test(css)) fail(`${file}: remote @import`);
  for (const [, dq, sq, bare] of css.matchAll(/url\(\s*(?:"([^"]*)"|'([^']*)'|([^)\s]*))\s*\)/g)) {
    const url = dq ?? sq ?? bare;
    if (isRemote(url)) fail(`${file}: third-party request url(${url})`);
    else if (
      !url.startsWith('data:') &&
      !url.startsWith('#') &&
      !existsSync(join(ROOT, dirname(file), localTarget(url)))
    )
      fail(`${file}: url(${url}) does not exist`);
  }
}

// 4. placeholders that must never ship
const PLACEHOLDERS = [/hello@example\.com/i, /\blorem ipsum\b/i];
const UNFINISHED = /\b(TODO|FIXME|XXX)\b/;
for (const file of tracked.filter((f) => !isVendored(f) && /\.(html|css|js|mjs|md|json|yml|yaml)$/.test(f))) {
  if (file === 'scripts/check-repo.mjs') continue;
  const content = text(file);
  for (const re of PLACEHOLDERS) if (re.test(content)) fail(`${file}: placeholder text matching ${re}`);
  if (/\.(html|css|js|mjs)$/.test(file) && UNFINISHED.test(content))
    fail(`${file}: leftover TODO/FIXME marker`);
}

// 5. obvious committed secrets (GitHub's secret scanning + push protection is the real net; see SECURITY.md)
const SECRETS = [
  [/AKIA[0-9A-Z]{16}/, 'AWS access key id'],
  [/gh[pousr]_[A-Za-z0-9]{36,}/, 'GitHub token'],
  [/github_pat_[A-Za-z0-9_]{50,}/, 'GitHub fine-grained token'],
  [/xox[abposr]-[A-Za-z0-9-]{10,}/, 'Slack token'],
  [/-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY-----/, 'private key'],
  [
    /(?:api[_-]?key|secret|token|passwd|password)\s*[:=]\s*['"][A-Za-z0-9_\-/+=]{24,}['"]/i,
    'hard-coded credential',
  ],
];
for (const file of tracked.filter((f) => !isVendored(f) && !/\.(png|woff2?)$/.test(f))) {
  const content = text(file);
  for (const [re, label] of SECRETS) if (re.test(content)) fail(`${file}: looks like a committed ${label}`);
}

// 6. optional: no AI co-author / generated-by trailers anywhere in reachable history
if (process.argv.includes('--history')) {
  const log = execFileSync('git', ['log', '--all', '--format=%H%x00%B%x01'], { cwd: ROOT, encoding: 'utf8' });
  const TRAILER =
    /^(co-authored-by:.*(claude|anthropic|copilot|chatgpt|openai|gemini)|generated (with|by)\b.*(claude|anthropic))/im;
  for (const entry of log.split('\x01')) {
    const [sha, body = ''] = entry.trim().split('\0');
    if (sha && TRAILER.test(body)) fail(`commit ${sha.slice(0, 7)} carries an AI attribution trailer`);
  }
}

if (problems.length) {
  console.error(`check:repo found ${problems.length} problem(s):\n - ${problems.join('\n - ')}`);
  process.exit(1);
}
console.log(
  `check:repo ok (${tracked.length} tracked files${process.argv.includes('--history') ? ', history clean' : ''}).`,
);
