#!/usr/bin/env node
// One source of truth for ORBIT's browser security headers. It generates, and verifies, every place the
// policy has to live:
//   vercel.json   response headers on Vercel
//   _headers      response headers on Netlify and Cloudflare Pages
//   index.html    <meta http-equiv="Content-Security-Policy"> for hosts that cannot set headers (GitHub Pages)
// The inline import map is allowed by hash, so the hash is recomputed here whenever the map changes.
//
//   npm run security:sync    rewrite the three files from the policy below
//   npm run security:check   fail if any of them drifted (runs in CI and in the unit tests)
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT } from './headers.mjs';

const IMPORT_MAP = /(<script type="importmap">)([\s\S]*?)(<\/script>)/;
const CSP_META = /[ \t]*<meta http-equiv="Content-Security-Policy" content="[^"]*">\n?/;

/** sha256 of the inline import map, exactly as the browser hashes it (the script element's text). */
export function importMapHash(html) {
  const map = html.match(IMPORT_MAP);
  if (!map) throw new Error('index.html has no <script type="importmap">');
  return `sha256-${createHash('sha256').update(map[2]).digest('base64')}`;
}

/**
 * The Content-Security-Policy. Everything is same-origin: scripts, styles, images and fonts are all
 * files in this repo, and the page makes no requests of its own (connect-src 'none'). The only inline
 * code is the import map, allowed by hash. `meta` drops directives a <meta> tag cannot carry.
 */
export function csp(hash, { meta = false } = {}) {
  return [
    "default-src 'self'",
    `script-src 'self' '${hash}'`,
    "style-src 'self'",
    "img-src 'self'",
    "font-src 'self'",
    "connect-src 'none'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    ...(meta ? [] : ["frame-ancestors 'none'"]),
  ].join('; ');
}

/** Response headers, in the order they are written. */
export function headers(hash) {
  return [
    ['Content-Security-Policy', csp(hash)],
    ['X-Content-Type-Options', 'nosniff'],
    ['Referrer-Policy', 'strict-origin-when-cross-origin'],
    // Only features browsers recognise: an unknown token makes Chromium log a console error.
    [
      'Permissions-Policy',
      'accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()',
    ],
    ['X-Frame-Options', 'DENY'],
    ['Cross-Origin-Opener-Policy', 'same-origin'],
    ['Strict-Transport-Security', 'max-age=31536000'],
  ];
}

/** What vercel.json, _headers and index.html must contain right now. */
export function expected(root = ROOT) {
  const html = readFileSync(join(root, 'index.html'), 'utf8');
  const hash = importMapHash(html);
  const list = headers(hash);

  const vercel = JSON.parse(readFileSync(join(root, 'vercel.json'), 'utf8'));
  vercel.headers = [{ source: '/(.*)', headers: list.map(([key, value]) => ({ key, value })) }];

  const headersFile = [
    '# Generated by scripts/security.mjs: edit the policy there, then run `npm run security:sync`.',
    '/*',
    ...list.map(([key, value]) => `  ${key}: ${value}`),
    '',
  ].join('\n');

  const tag = `  <meta http-equiv="Content-Security-Policy" content="${csp(hash, { meta: true })}">\n`;
  const withoutTag = html.replace(CSP_META, '');
  const viewport = /[ \t]*<meta name="viewport"[^>]*>\n/;
  if (!viewport.test(withoutTag))
    throw new Error('index.html needs a <meta name="viewport"> to anchor the CSP tag');
  const newHtml = withoutTag.replace(viewport, (line) => line + tag);

  return { hash, vercel: `${JSON.stringify(vercel, null, 2)}\n`, headersFile, html: newHtml };
}

const FILES = { vercel: 'vercel.json', headersFile: '_headers', html: 'index.html' };

function run(check) {
  const want = expected();
  const stale = [];
  for (const [key, file] of Object.entries(FILES)) {
    let have = null;
    try {
      have = readFileSync(join(ROOT, file), 'utf8');
    } catch {
      /* missing */
    }
    if (have === want[key]) continue;
    if (check) stale.push(file);
    else writeFileSync(join(ROOT, file), want[key]);
  }
  if (check) {
    if (stale.length) {
      console.error(`Security headers are out of sync in: ${stale.join(', ')}\nFix: npm run security:sync`);
      process.exit(1);
    }
    console.log(`security headers in sync (import map ${want.hash}).`);
  } else {
    console.log(`wrote ${Object.values(FILES).join(', ')} (import map ${want.hash}).`);
  }
}

if (import.meta.url === new URL(process.argv[1], 'file://').href) run(process.argv.includes('--check'));
